# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz/ventana_marca.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_Marca(object):
    def setupUi(self, ventana_Marca):
        ventana_Marca.setObjectName("ventana_Marca")
        ventana_Marca.resize(426, 384)
        ventana_Marca.setMinimumSize(QtCore.QSize(426, 384))
        ventana_Marca.setMaximumSize(QtCore.QSize(426, 384))
        ventana_Marca.setStyleSheet("QDialog{\n"
"background-color:#000000\n"
"}")
        self.bt_SeleccionarMarca = QtWidgets.QPushButton(ventana_Marca)
        self.bt_SeleccionarMarca.setGeometry(QtCore.QRect(326, 60, 93, 28))
        self.bt_SeleccionarMarca.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_SeleccionarMarca.setObjectName("bt_SeleccionarMarca")
        self.label = QtWidgets.QLabel(ventana_Marca)
        self.label.setGeometry(QtCore.QRect(0, 10, 421, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color:#39ffa3\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bt_AgregarMarca = QtWidgets.QPushButton(ventana_Marca)
        self.bt_AgregarMarca.setGeometry(QtCore.QRect(326, 110, 93, 28))
        self.bt_AgregarMarca.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_AgregarMarca.setObjectName("bt_AgregarMarca")
        self.listView_marcas = QtWidgets.QListView(ventana_Marca)
        self.listView_marcas.setGeometry(QtCore.QRect(6, 51, 311, 321))
        self.listView_marcas.setObjectName("listView_marcas")

        self.retranslateUi(ventana_Marca)
        QtCore.QMetaObject.connectSlotsByName(ventana_Marca)

    def retranslateUi(self, ventana_Marca):
        _translate = QtCore.QCoreApplication.translate
        ventana_Marca.setWindowTitle(_translate("ventana_Marca", "Dialog"))
        self.bt_SeleccionarMarca.setText(_translate("ventana_Marca", "Seleccionar"))
        self.label.setText(_translate("ventana_Marca", "MARCAS"))
        self.bt_AgregarMarca.setText(_translate("ventana_Marca", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_Marca = QtWidgets.QDialog()
    ui = Ui_ventana_Marca()
    ui.setupUi(ventana_Marca)
    ventana_Marca.show()
    sys.exit(app.exec_())
