# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz/ventana_nueva_categoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_nueva_categoria(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(422, 177)
        Dialog.setMinimumSize(QtCore.QSize(422, 177))
        Dialog.setMaximumSize(QtCore.QSize(422, 177))
        Dialog.setStyleSheet("QDialog{\n"
"background-color:#ffffff\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 421, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color:#39ffa3\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_nuevoCodCategoria = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nuevoCodCategoria.setEnabled(False)
        self.lineEdit_nuevoCodCategoria.setGeometry(QtCore.QRect(140, 50, 241, 22))
        self.lineEdit_nuevoCodCategoria.setDragEnabled(False)
        self.lineEdit_nuevoCodCategoria.setObjectName("lineEdit_nuevoCodCategoria")
        self.lineEdit_nuevoCodCategoria_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nuevoCodCategoria_2.setGeometry(QtCore.QRect(140, 90, 241, 22))
        self.lineEdit_nuevoCodCategoria_2.setObjectName("lineEdit_nuevoCodCategoria_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bt_GuardarCategoria = QtWidgets.QPushButton(Dialog)
        self.bt_GuardarCategoria.setGeometry(QtCore.QRect(120, 130, 93, 28))
        self.bt_GuardarCategoria.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_GuardarCategoria.setObjectName("bt_GuardarCategoria")
        self.bt_CancelarCategoria = QtWidgets.QPushButton(Dialog)
        self.bt_CancelarCategoria.setGeometry(QtCore.QRect(240, 130, 93, 28))
        self.bt_CancelarCategoria.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_CancelarCategoria.setObjectName("bt_CancelarCategoria")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "NUEVA CATEGORIA"))
        self.label_2.setText(_translate("Dialog", "Codigo:"))
        self.label_3.setText(_translate("Dialog", "Descripción:"))
        self.bt_GuardarCategoria.setText(_translate("Dialog", "Guardar"))
        self.bt_CancelarCategoria.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ventana_nueva_categoria()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
