# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz/ventana_datos_empresa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_Datos_Empresa(object):
    def setupUi(self, ventana_Datos_Empresa):
        ventana_Datos_Empresa.setObjectName("ventana_Datos_Empresa")
        ventana_Datos_Empresa.resize(750, 510)
        ventana_Datos_Empresa.setMinimumSize(QtCore.QSize(750, 510))
        ventana_Datos_Empresa.setMaximumSize(QtCore.QSize(750, 510))
        ventana_Datos_Empresa.setStyleSheet("QLineEdit{\n"
"border-radius:10px;\n"
"border:2px solid rgb(114, 117, 126)\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border-radius:10px;\n"
"border:2px solid rgb(44, 182, 125)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border-radius:10px;\n"
"border:2px solid rgb(127, 90, 240)\n"
"}")
        self.labelArticulo_2 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.labelArticulo_2.setGeometry(QtCore.QRect(10, 10, 431, 40))
        self.labelArticulo_2.setMinimumSize(QtCore.QSize(0, 40))
        self.labelArticulo_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelArticulo_2.setFont(font)
        self.labelArticulo_2.setStyleSheet("QLabel{\n"
"background-color:#46858b;\n"
"color:#ffffff\n"
"}")
        self.labelArticulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArticulo_2.setObjectName("labelArticulo_2")
        self.label = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label.setGeometry(QtCore.QRect(20, 70, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_razon_social_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_razon_social_empresa.setGeometry(QtCore.QRect(180, 70, 261, 22))
        self.lineEdit_razon_social_empresa.setObjectName("lineEdit_razon_social_empresa")
        self.label_2 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_nombre_fantasia_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_nombre_fantasia_empresa.setGeometry(QtCore.QRect(180, 110, 261, 22))
        self.lineEdit_nombre_fantasia_empresa.setObjectName("lineEdit_nombre_fantasia_empresa")
        self.label_3 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_cuit_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_cuit_empresa.setGeometry(QtCore.QRect(180, 150, 261, 22))
        self.lineEdit_cuit_empresa.setObjectName("lineEdit_cuit_empresa")
        self.label_4 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_iibb_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_iibb_empresa.setGeometry(QtCore.QRect(180, 230, 261, 22))
        self.lineEdit_iibb_empresa.setObjectName("lineEdit_iibb_empresa")
        self.label_5 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_inicio_actividades_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_inicio_actividades_empresa.setGeometry(QtCore.QRect(180, 270, 261, 22))
        self.lineEdit_inicio_actividades_empresa.setObjectName("lineEdit_inicio_actividades_empresa")
        self.label_6 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_domicilio_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_domicilio_empresa.setGeometry(QtCore.QRect(180, 310, 261, 22))
        self.lineEdit_domicilio_empresa.setObjectName("lineEdit_domicilio_empresa")
        self.label_7 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_localidad_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_localidad_empresa.setGeometry(QtCore.QRect(180, 350, 261, 22))
        self.lineEdit_localidad_empresa.setObjectName("lineEdit_localidad_empresa")
        self.label_8 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_8.setGeometry(QtCore.QRect(20, 390, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_provincia_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_provincia_empresa.setGeometry(QtCore.QRect(180, 390, 261, 22))
        self.lineEdit_provincia_empresa.setObjectName("lineEdit_provincia_empresa")
        self.label_9 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_9.setGeometry(QtCore.QRect(20, 430, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_pais_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_pais_empresa.setGeometry(QtCore.QRect(180, 430, 261, 22))
        self.lineEdit_pais_empresa.setObjectName("lineEdit_pais_empresa")
        self.bt_grabar_datos_empresa = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_grabar_datos_empresa.setGeometry(QtCore.QRect(130, 470, 93, 30))
        self.bt_grabar_datos_empresa.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_grabar_datos_empresa.setFont(font)
        self.bt_grabar_datos_empresa.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_grabar_datos_empresa.setObjectName("bt_grabar_datos_empresa")
        self.bt_cancelar_datos_empresa = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_cancelar_datos_empresa.setGeometry(QtCore.QRect(240, 470, 93, 30))
        self.bt_cancelar_datos_empresa.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_cancelar_datos_empresa.setFont(font)
        self.bt_cancelar_datos_empresa.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_cancelar_datos_empresa.setObjectName("bt_cancelar_datos_empresa")
        self.label_10 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_categoria_empresa = QtWidgets.QLineEdit(ventana_Datos_Empresa)
        self.lineEdit_categoria_empresa.setGeometry(QtCore.QRect(180, 190, 261, 22))
        self.lineEdit_categoria_empresa.setObjectName("lineEdit_categoria_empresa")
        self.bt_modificar_datos_empresa = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_modificar_datos_empresa.setGeometry(QtCore.QRect(20, 470, 93, 30))
        self.bt_modificar_datos_empresa.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_modificar_datos_empresa.setFont(font)
        self.bt_modificar_datos_empresa.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_modificar_datos_empresa.setObjectName("bt_modificar_datos_empresa")
        self.bt_eliminar_datos_empresa_2 = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_eliminar_datos_empresa_2.setGeometry(QtCore.QRect(350, 470, 93, 30))
        self.bt_eliminar_datos_empresa_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_eliminar_datos_empresa_2.setFont(font)
        self.bt_eliminar_datos_empresa_2.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_eliminar_datos_empresa_2.setObjectName("bt_eliminar_datos_empresa_2")
        self.bt_cambiar_datos_empresa = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_cambiar_datos_empresa.setGeometry(QtCore.QRect(400, 13, 30, 30))
        self.bt_cambiar_datos_empresa.setMinimumSize(QtCore.QSize(30, 30))
        self.bt_cambiar_datos_empresa.setMaximumSize(QtCore.QSize(30, 30))
        self.bt_cambiar_datos_empresa.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Interfaz\\elipsis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cambiar_datos_empresa.setIcon(icon)
        self.bt_cambiar_datos_empresa.setIconSize(QtCore.QSize(38, 38))
        self.bt_cambiar_datos_empresa.setObjectName("bt_cambiar_datos_empresa")
        self.bt_subir_foto_empresa = QtWidgets.QPushButton(ventana_Datos_Empresa)
        self.bt_subir_foto_empresa.setGeometry(QtCore.QRect(570, 315, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setBold(True)
        font.setWeight(75)
        self.bt_subir_foto_empresa.setFont(font)
        self.bt_subir_foto_empresa.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_subir_foto_empresa.setObjectName("bt_subir_foto_empresa")
        self.label_11 = QtWidgets.QLabel(ventana_Datos_Empresa)
        self.label_11.setGeometry(QtCore.QRect(510, 100, 200, 200))
        self.label_11.setMinimumSize(QtCore.QSize(200, 200))
        self.label_11.setMaximumSize(QtCore.QSize(200, 200))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Interfaz\\no-disponible.png"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.line = QtWidgets.QFrame(ventana_Datos_Empresa)
        self.line.setGeometry(QtCore.QRect(510, 290, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(ventana_Datos_Empresa)
        self.line_2.setGeometry(QtCore.QRect(510, 90, 201, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(ventana_Datos_Empresa)
        self.line_3.setGeometry(QtCore.QRect(500, 100, 20, 201))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(ventana_Datos_Empresa)
        self.line_4.setGeometry(QtCore.QRect(700, 100, 20, 201))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.retranslateUi(ventana_Datos_Empresa)
        QtCore.QMetaObject.connectSlotsByName(ventana_Datos_Empresa)

    def retranslateUi(self, ventana_Datos_Empresa):
        _translate = QtCore.QCoreApplication.translate
        ventana_Datos_Empresa.setWindowTitle(_translate("ventana_Datos_Empresa", "Form"))
        self.labelArticulo_2.setText(_translate("ventana_Datos_Empresa", "DATOS EMPRESA"))
        self.label.setText(_translate("ventana_Datos_Empresa", "Razon Social:"))
        self.label_2.setText(_translate("ventana_Datos_Empresa", "Nombre Fantasía:"))
        self.label_3.setText(_translate("ventana_Datos_Empresa", "CUIT:"))
        self.label_4.setText(_translate("ventana_Datos_Empresa", "Ingresos Brutos:"))
        self.label_5.setText(_translate("ventana_Datos_Empresa", "Inicio Actividades:"))
        self.label_6.setText(_translate("ventana_Datos_Empresa", "Domicilio:"))
        self.label_7.setText(_translate("ventana_Datos_Empresa", "Localidad:"))
        self.label_8.setText(_translate("ventana_Datos_Empresa", "Provincia:"))
        self.label_9.setText(_translate("ventana_Datos_Empresa", "País:"))
        self.bt_grabar_datos_empresa.setText(_translate("ventana_Datos_Empresa", "GRABAR"))
        self.bt_cancelar_datos_empresa.setText(_translate("ventana_Datos_Empresa", "CANCELAR"))
        self.label_10.setText(_translate("ventana_Datos_Empresa", "Categoría:"))
        self.bt_modificar_datos_empresa.setText(_translate("ventana_Datos_Empresa", "MODIFICAR"))
        self.bt_eliminar_datos_empresa_2.setText(_translate("ventana_Datos_Empresa", "ELIMINAR"))
        self.bt_subir_foto_empresa.setText(_translate("ventana_Datos_Empresa", "SUBIR LOGO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_Datos_Empresa = QtWidgets.QWidget()
    ui = Ui_ventana_Datos_Empresa()
    ui.setupUi(ventana_Datos_Empresa)
    ventana_Datos_Empresa.show()
    sys.exit(app.exec_())
