# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_categoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_Categorias(object):
    def setupUi(self, ventana_Categorias):
        ventana_Categorias.setObjectName("ventana_Categorias")
        ventana_Categorias.resize(429, 386)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventana_Categorias.sizePolicy().hasHeightForWidth())
        ventana_Categorias.setSizePolicy(sizePolicy)
        ventana_Categorias.setMinimumSize(QtCore.QSize(429, 386))
        ventana_Categorias.setMaximumSize(QtCore.QSize(429, 386))
        ventana_Categorias.setStyleSheet("QDialog{\n"
"background-color:#000000\n"
"}")
        self.label = QtWidgets.QLabel(ventana_Categorias)
        self.label.setGeometry(QtCore.QRect(4, 10, 421, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color:#39ffa3\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listView_categorias = QtWidgets.QListView(ventana_Categorias)
        self.listView_categorias.setGeometry(QtCore.QRect(10, 51, 311, 321))
        self.listView_categorias.setObjectName("listView_categorias")
        self.bt_SeleccionarCategoria = QtWidgets.QPushButton(ventana_Categorias)
        self.bt_SeleccionarCategoria.setGeometry(QtCore.QRect(330, 60, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setBold(True)
        font.setWeight(75)
        self.bt_SeleccionarCategoria.setFont(font)
        self.bt_SeleccionarCategoria.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_SeleccionarCategoria.setObjectName("bt_SeleccionarCategoria")
        self.bt_AgregarCategoria = QtWidgets.QPushButton(ventana_Categorias)
        self.bt_AgregarCategoria.setGeometry(QtCore.QRect(330, 110, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setBold(True)
        font.setWeight(75)
        self.bt_AgregarCategoria.setFont(font)
        self.bt_AgregarCategoria.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_AgregarCategoria.setObjectName("bt_AgregarCategoria")

        self.retranslateUi(ventana_Categorias)
        QtCore.QMetaObject.connectSlotsByName(ventana_Categorias)

    def retranslateUi(self, ventana_Categorias):
        _translate = QtCore.QCoreApplication.translate
        ventana_Categorias.setWindowTitle(_translate("ventana_Categorias", "Dialog"))
        self.label.setText(_translate("ventana_Categorias", "CATEGORIAS"))
        self.bt_SeleccionarCategoria.setText(_translate("ventana_Categorias", "Seleccionar"))
        self.bt_AgregarCategoria.setText(_translate("ventana_Categorias", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_Categorias = QtWidgets.QDialog()
    ui = Ui_ventana_Categorias()
    ui.setupUi(ventana_Categorias)
    ventana_Categorias.show()
    sys.exit(app.exec_())
