# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_agregar_articulo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_agregar_articulo(object):
    def setupUi(self, ventana_agregar_articulo):
        ventana_agregar_articulo.setObjectName("ventana_agregar_articulo")
        ventana_agregar_articulo.resize(870, 589)
        ventana_agregar_articulo.setMinimumSize(QtCore.QSize(870, 589))
        ventana_agregar_articulo.setMaximumSize(QtCore.QSize(870, 589))
        ventana_agregar_articulo.setStyleSheet("QDialog{\n"
"background-color:#000000\n"
"}")
        self.lineEdit_BuscarArticuloFacturaNueva = QtWidgets.QLineEdit(ventana_agregar_articulo)
        self.lineEdit_BuscarArticuloFacturaNueva.setGeometry(QtCore.QRect(12, 40, 361, 30))
        self.lineEdit_BuscarArticuloFacturaNueva.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_BuscarArticuloFacturaNueva.setPalette(palette)
        self.lineEdit_BuscarArticuloFacturaNueva.setStyleSheet("QLineEdit{\n"
"background-color:#ffffff;\n"
"}")
        self.lineEdit_BuscarArticuloFacturaNueva.setObjectName("lineEdit_BuscarArticuloFacturaNueva")
        self.bt_AgregarArticuloNvaFactura = QtWidgets.QPushButton(ventana_agregar_articulo)
        self.bt_AgregarArticuloNvaFactura.setGeometry(QtCore.QRect(380, 40, 93, 30))
        self.bt_AgregarArticuloNvaFactura.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_AgregarArticuloNvaFactura.setFont(font)
        self.bt_AgregarArticuloNvaFactura.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_AgregarArticuloNvaFactura.setObjectName("bt_AgregarArticuloNvaFactura")
        self.tableWidget_SelecionarArticuloFactura = QtWidgets.QTableWidget(ventana_agregar_articulo)
        self.tableWidget_SelecionarArticuloFactura.setGeometry(QtCore.QRect(10, 90, 851, 491))
        self.tableWidget_SelecionarArticuloFactura.setStyleSheet("QTableView{\n"
"color: #000 ;\n"
"text-align: center;\n"
"padding: 5px;\n"
"margin: 3px;\n"
"border-radius: 5px;\n"
"font-size: 14px;\n"
"background-color: #FFF2F1FC; \n"
"}\n"
"\n"
"QTableView QTableCornerButton::section {\n"
"       border-top-left-radius: 5px;\n"
"    border: 0.5px solid #6c6c6c;\n"
" background-color: #BF060C26; \n"
"}\n"
"QTableView QHeaderView::section::last:horizontal{\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"\n"
"QTableView QHeaderView::section::first:horizontal {\n"
"    border-top-left-radius: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
" QTableView ::section{\n"
"    padding: 2px 5px ;\n"
"    color: #D9D9D9 ;\n"
"      qproperty-alignment: AlignCenter;\n"
"    border: 1px solid grey;\n"
"    background-color:#1f232a;\n"
"    height: 35;\n"
"}\n"
"\n"
"\n"
" QTableView QHeaderView::section:vertical {\n"
" border: 0.5px solid #6c6c6c;\n"
"    padding: 1px;\n"
"  font-weight: bold; /* Poner en negrita */\n"
"  font-size: 10px; /* Tamaño de la letra */\n"
"  padding: 1px;\n"
"color: #FFEFEEFA;\n"
" background-color: #BF060C26; \n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"\n"
"/*\n"
"QTableView::item:selected {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"*/\n"
"\n"
"/*\n"
"QTableView::item:selected:!focus {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"*/\n"
"\n"
"QHeaderView { \n"
"qproperty-defaultAlignment: AlignCenter; \n"
"}\n"
"\n"
"    /* centrar titulos y dar padding */\n"
"QTableView QHeaderView::section:horizontal {\n"
"  font-weight: bold; /* Poner en negrita */\n"
"  font-size: 14px; /* Tamaño de la letra */\n"
" /* padding: 2px 5px ;\n"
"  margin: 2px;*/\n"
"   text-align: center;\n"
"    padding: 2px;\n"
"  color: #FFEFEEFA;\n"
" border: 0.5px solid #6c6c6c;\n"
" background-color: #BF060C26;\n"
"}\n"
"")
        self.tableWidget_SelecionarArticuloFactura.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_SelecionarArticuloFactura.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_SelecionarArticuloFactura.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_SelecionarArticuloFactura.setObjectName("tableWidget_SelecionarArticuloFactura")
        self.tableWidget_SelecionarArticuloFactura.setColumnCount(10)
        self.tableWidget_SelecionarArticuloFactura.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_SelecionarArticuloFactura.setHorizontalHeaderItem(9, item)

        self.retranslateUi(ventana_agregar_articulo)
        QtCore.QMetaObject.connectSlotsByName(ventana_agregar_articulo)

    def retranslateUi(self, ventana_agregar_articulo):
        _translate = QtCore.QCoreApplication.translate
        ventana_agregar_articulo.setWindowTitle(_translate("ventana_agregar_articulo", "Dialog"))
        self.bt_AgregarArticuloNvaFactura.setText(_translate("ventana_agregar_articulo", "AGREGAR"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(0)
        item.setText(_translate("ventana_agregar_articulo", "CODIGO"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(1)
        item.setText(_translate("ventana_agregar_articulo", "PRODUCTO"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(2)
        item.setText(_translate("ventana_agregar_articulo", "MODELO"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(3)
        item.setText(_translate("ventana_agregar_articulo", "MARCA"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(4)
        item.setText(_translate("ventana_agregar_articulo", "CATEGORIA"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(5)
        item.setText(_translate("ventana_agregar_articulo", "PRECIO_COSTO"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(6)
        item.setText(_translate("ventana_agregar_articulo", "PRECIO_VENTA"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(7)
        item.setText(_translate("ventana_agregar_articulo", "IVA"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(8)
        item.setText(_translate("ventana_agregar_articulo", "STOCK"))
        item = self.tableWidget_SelecionarArticuloFactura.horizontalHeaderItem(9)
        item.setText(_translate("ventana_agregar_articulo", "MARGEN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_agregar_articulo = QtWidgets.QDialog()
    ui = Ui_ventana_agregar_articulo()
    ui.setupUi(ventana_agregar_articulo)
    ventana_agregar_articulo.show()
    sys.exit(app.exec_())
