# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_agregar_item_factura.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_agregarItemFactura(object):
    def setupUi(self, ventana_agregarItemFactura):
        ventana_agregarItemFactura.setObjectName("ventana_agregarItemFactura")
        ventana_agregarItemFactura.resize(1031, 631)
        ventana_agregarItemFactura.setMinimumSize(QtCore.QSize(1031, 631))
        ventana_agregarItemFactura.setMaximumSize(QtCore.QSize(1031, 631))
        ventana_agregarItemFactura.setStyleSheet("QDialog{\n"
"background-color:#000000\n"
"}")
        self.lineEdit_BuscarItemArticuloNvaFactura = QtWidgets.QLineEdit(ventana_agregarItemFactura)
        self.lineEdit_BuscarItemArticuloNvaFactura.setGeometry(QtCore.QRect(12, 90, 361, 30))
        self.lineEdit_BuscarItemArticuloNvaFactura.setMinimumSize(QtCore.QSize(0, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_BuscarItemArticuloNvaFactura.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_BuscarItemArticuloNvaFactura.setFont(font)
        self.lineEdit_BuscarItemArticuloNvaFactura.setStyleSheet("QLineEdit{\n"
"background-color:#ffffff;\n"
"}")
        self.lineEdit_BuscarItemArticuloNvaFactura.setObjectName("lineEdit_BuscarItemArticuloNvaFactura")
        self.bt_BuscarItemArticuloNvaFactura = QtWidgets.QPushButton(ventana_agregarItemFactura)
        self.bt_BuscarItemArticuloNvaFactura.setGeometry(QtCore.QRect(380, 90, 93, 30))
        self.bt_BuscarItemArticuloNvaFactura.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Orbitron SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BuscarItemArticuloNvaFactura.setFont(font)
        self.bt_BuscarItemArticuloNvaFactura.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_BuscarItemArticuloNvaFactura.setObjectName("bt_BuscarItemArticuloNvaFactura")
        self.tableWidgetAgregarArtNvaFactura = QtWidgets.QTableWidget(ventana_agregarItemFactura)
        self.tableWidgetAgregarArtNvaFactura.setGeometry(QtCore.QRect(10, 140, 1011, 481))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableWidgetAgregarArtNvaFactura.setFont(font)
        self.tableWidgetAgregarArtNvaFactura.setStyleSheet("QTableView{\n"
"color: #000 ;\n"
"text-align: center;\n"
"padding: 5px;\n"
"margin: 3px;\n"
"border-radius: 5px;\n"
"font-size: 14px;\n"
"background-color: #FFF2F1FC; \n"
"}\n"
"\n"
"QTableView QTableCornerButton::section {\n"
"       border-top-left-radius: 5px;\n"
"    border: 0.5px solid #6c6c6c;\n"
" background-color: #BF060C26; \n"
"}\n"
"QTableView QHeaderView::section::last:horizontal{\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"\n"
"QTableView QHeaderView::section::first:horizontal {\n"
"    border-top-left-radius: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
" QTableView ::section{\n"
"    padding: 2px 5px ;\n"
"    color: #D9D9D9 ;\n"
"      qproperty-alignment: AlignCenter;\n"
"    border: 1px solid grey;\n"
"    background-color:#1f232a;\n"
"    height: 35;\n"
"}\n"
"\n"
"\n"
" QTableView QHeaderView::section:vertical {\n"
" border: 0.5px solid #6c6c6c;\n"
"    padding: 1px;\n"
"  font-weight: bold; /* Poner en negrita */\n"
"  font-size: 10px; /* Tamaño de la letra */\n"
"  padding: 1px;\n"
"color: #FFEFEEFA;\n"
" background-color: #BF060C26; \n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"\n"
"/*\n"
"QTableView::item:selected {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"*/\n"
"\n"
"/*\n"
"QTableView::item:selected:!focus {\n"
"    background-color:#FF1EB0ED;\n"
"    color: white;\n"
"}\n"
"*/\n"
"\n"
"QHeaderView { \n"
"qproperty-defaultAlignment: AlignCenter; \n"
"}\n"
"\n"
"    /* centrar titulos y dar padding */\n"
"QTableView QHeaderView::section:horizontal {\n"
"  font-weight: bold; /* Poner en negrita */\n"
"  font-size: 14px; /* Tamaño de la letra */\n"
" /* padding: 2px 5px ;\n"
"  margin: 2px;*/\n"
"   text-align: center;\n"
"    padding: 2px;\n"
"  color: #FFEFEEFA;\n"
" border: 0.5px solid #6c6c6c;\n"
" background-color: #BF060C26;\n"
"}\n"
"")
        self.tableWidgetAgregarArtNvaFactura.setObjectName("tableWidgetAgregarArtNvaFactura")
        self.tableWidgetAgregarArtNvaFactura.setColumnCount(8)
        self.tableWidgetAgregarArtNvaFactura.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAgregarArtNvaFactura.setHorizontalHeaderItem(7, item)
        self.labelArticulo_2 = QtWidgets.QLabel(ventana_agregarItemFactura)
        self.labelArticulo_2.setGeometry(QtCore.QRect(10, 10, 1011, 40))
        self.labelArticulo_2.setMinimumSize(QtCore.QSize(0, 40))
        self.labelArticulo_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelArticulo_2.setFont(font)
        self.labelArticulo_2.setStyleSheet("QLabel{\n"
"background-color:#46858b;\n"
"color:#ffffff\n"
"}")
        self.labelArticulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArticulo_2.setObjectName("labelArticulo_2")

        self.retranslateUi(ventana_agregarItemFactura)
        QtCore.QMetaObject.connectSlotsByName(ventana_agregarItemFactura)

    def retranslateUi(self, ventana_agregarItemFactura):
        _translate = QtCore.QCoreApplication.translate
        ventana_agregarItemFactura.setWindowTitle(_translate("ventana_agregarItemFactura", "Dialog"))
        self.bt_BuscarItemArticuloNvaFactura.setText(_translate("ventana_agregarItemFactura", "BUSCAR"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(0)
        item.setText(_translate("ventana_agregarItemFactura", "CODIGO"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(1)
        item.setText(_translate("ventana_agregarItemFactura", "NOMBRE"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(2)
        item.setText(_translate("ventana_agregarItemFactura", "MODELO"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(3)
        item.setText(_translate("ventana_agregarItemFactura", "PRECIO_COSTO"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(4)
        item.setText(_translate("ventana_agregarItemFactura", "PRECIO_VENTA"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(5)
        item.setText(_translate("ventana_agregarItemFactura", "IVA"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(6)
        item.setText(_translate("ventana_agregarItemFactura", "MARGEN"))
        item = self.tableWidgetAgregarArtNvaFactura.horizontalHeaderItem(7)
        item.setText(_translate("ventana_agregarItemFactura", "STOCK"))
        self.labelArticulo_2.setText(_translate("ventana_agregarItemFactura", "AGREGAR ARTICULO A LA FACTURA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_agregarItemFactura = QtWidgets.QDialog()
    ui = Ui_ventana_agregarItemFactura()
    ui.setupUi(ventana_agregarItemFactura)
    ventana_agregarItemFactura.show()
    sys.exit(app.exec_())
