# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_proveedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_proveedores(object):
    def setupUi(self, ventana_proveedores):
        ventana_proveedores.setObjectName("ventana_proveedores")
        ventana_proveedores.resize(356, 377)
        ventana_proveedores.setStyleSheet("QDialog{\n"
"background-color:#000000\n"
"}")
        self.bt_SeleccionarProveedor = QtWidgets.QPushButton(ventana_proveedores)
        self.bt_SeleccionarProveedor.setGeometry(QtCore.QRect(260, 90, 93, 28))
        self.bt_SeleccionarProveedor.setStyleSheet("QPushButton{\n"
"background-color:#2caeff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#39ffa3;\n"
"}")
        self.bt_SeleccionarProveedor.setObjectName("bt_SeleccionarProveedor")
        self.label = QtWidgets.QLabel(ventana_proveedores)
        self.label.setGeometry(QtCore.QRect(0, 10, 361, 30))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Goldman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color:#39ffa3\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listView_proveedores = QtWidgets.QListView(ventana_proveedores)
        self.listView_proveedores.setGeometry(QtCore.QRect(10, 50, 241, 321))
        self.listView_proveedores.setObjectName("listView_proveedores")

        self.retranslateUi(ventana_proveedores)
        QtCore.QMetaObject.connectSlotsByName(ventana_proveedores)

    def retranslateUi(self, ventana_proveedores):
        _translate = QtCore.QCoreApplication.translate
        ventana_proveedores.setWindowTitle(_translate("ventana_proveedores", "Dialog"))
        self.bt_SeleccionarProveedor.setText(_translate("ventana_proveedores", "Seleccionar"))
        self.label.setText(_translate("ventana_proveedores", "PROVEEDORES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_proveedores = QtWidgets.QDialog()
    ui = Ui_ventana_proveedores()
    ui.setupUi(ventana_proveedores)
    ventana_proveedores.show()
    sys.exit(app.exec_())
